### ISSUE TITLE
Add option to default values

### ISSUE THREAD

**Issue by KristjanESPERANTO** [kounch/argonone#11]
It would be nice if there was an option to reset to the default values. So you don't have to dig out the manual to look for it.

For Argon One Pi 4 V2 the values are: 55°C = 10%, 60°C = 55% and 65°C = 100%.

**Comment by kounch** [comment]
I'm sorry, but i don't think that i will dedicate more time to this project. However, you're welcome to make your own changes and I will be happy to accept them.
