### ISSUE TITLE
The service fails to start

### ISSUE THREAD

**Issue by georgikoemdzhiev** [kounch/argonone#13]
Hello, 

I tried to run the service on Arch (Manjaro) linux but it seems it fails with Status 1. See the output from `systemctl status`:

```log
[manjaro@manjaro argonone]$ sudo systemctl status argononed.service
× argononed.service - Argon One Fan and Button Service
     Loaded: loaded (/usr/lib/systemd/system/argononed.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Mon 2023-08-07 10:34:20 BST; 34s ago
   Duration: 113ms
    Process: 123285 ExecStart=/opt/argonone/bin/python3 /opt/argonone/bin/argononed.py (code=exited, status=1/FAILURE)
   Main PID: 123285 (code=exited, status=1/FAILURE)
        CPU: 113ms
```

I installed the service manually following those steps:
1. git clone -b feature/RaspberryPi4 https://github.com/kounch/argonone.git
2. ran `makepkg -si`

Kernel Version and system info: Linux manjaro 6.1.37-1-MANJARO-ARM-RPI
Distribution and Version: Manjaro ARM Linux, v23.02

**Comment by kounch** [comment]
This code is no longer maintained
