### ISSUE TITLE
Does not work with Manjaro/RPI3 (possible GPIO error)

### ISSUE THREAD

**Issue by thegeek1977** [kounch/argonone#2]
Hi Devs.

Iøve contributed to the RPI4-branch of this software.

However i got a RPI3 laying around ready to be used for server purposes and as such I got the Argon One case for the RPI3 for christmaspressent and thought installing the Argon3-software in Manjaro for the RPI3.

However something must have broke after you wrote it because it will no longer work.

First off the rpi.gpio-module complains that it aint not working on anything but a Raspberry Pi (although that is exactly what i am trying to install the suite on), hovever it can be "faked into semiworking" by bind-mounting a fake version of cpuinfo into /proc/cpuinfo containing some misssing information  about the model of the CPU and a fake serial but it wont stll not work.

When the server is then started it will throw the error "export_store: invalid GPIO 4"  I cannot find a remedy for this. I can get the fan to work but the power-button and shutdown vill not work at all.

Works a treat on the RPI4 with my patches though. Can you please look into this and try to find a workaround or something or at least tell me what I could do? Clearly something is up with RPI.GPIO
on RPI3 but what could be done? Is it pissible to communicate with the help from another module or...???

If you come up with something I'll gladly test and help as much as I can (I am not a python-programmer but will do what I can to help)

Thank you very much.

**Comment by kounch** [comment]
I'm sorry, but i don't think that i will dedicate more time to this project.
