### ISSUE TITLE
Fan speed vs. loudness

### ISSUE THREAD

**Issue by RipperFox** [kounch/argonone#3]
I played a little with the fan speed settings via a python script and noticed that there's almost no difference in fan noise in the range from 3% to 100%.

With 2% it's kind of in the middle and only with the 1% speed setting the fan is "quiet".

Is there a possibility to control the fan speed in a more granular way? I guess the fan control circuit has to be changed a little..

**Comment by kounch** [comment]
I think you should ask the manufacturer
