### ISSUE TITLE
Bug: RPi.GPIO module could not be loaded on Pi4

### ISSUE THREAD

**Issue by r4thrida** [kounch/argonone#8]
With Python 3.8 installed. I have tried this pkg, the argonone daemon failed so went a head with manually importing the module via Python. Ended up with following error. 

>>> import RPi.GPIO as GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: This module can only be run on a Raspberry Pi!

My system is built on 64bit arch on Pi4. I have tried adding cflags as gcc10 needs it; this didn't help.
Tried first installing the python-raspberry-gpio.git with same error.

Any advise would help. thx.

**Comment by r4thrida** [comment]
I see the issue with 64 bit arch linux on arm. the 32 bit OS works fine. Seems like Kernel built for 64 bit doesnot provide hardware info in /proc/cpuinfo causing RPi.GPIO library to choke as RuntimeError:This module can only be run on a Raspberry Pi!.... Work around was proposed as to create a Fake-cpuinfo and mount --bind /root/Fake-cpuinfo /proc/cpuinfo ... this didn't work for 64 bit.

**Comment by FossPrime** [comment]
@r4thrida Im also running an Argon One with a Raspberry Pi 4 and Ubuntu x64 bit.

I think the issue might be related to moved dependencies
The maintainer is working on this https://www.raspberrypi.org/forums/viewtopic.php?t=244375#p1490477
I tried the new version and that worked.

This guy provides some good insight into what might be going on... such as needing to use Python3 etc
https://github.com/meuter/argon-one-case-ubuntu-20.04
that script version worked on my ubuntu server distro
